parameters:
- name: creds
  type: string
- name: resourceUrl
  type: string
  default: 'Any CPU'
- name: resourceTypeName
  type: string
  default: 'Arm'
- name: stepName
  type: string
  default: 'resource-login'
- name: varName
  type: string
  default: 'token'

steps:
- task: AzurePowerShell@5
  name: ${{ parameters.stepName }}
  displayName: 'Adquiring Access Token for ${{ parameters.resourceUrl }}'
  inputs:
    azureSubscription: ${{ parameters.creds }}
    azurePowerShellVersion: LatestVersion
    script: |
      $resourceToken = scripts/actions/azure-resource-login/Get-AzResourceAccessToken.ps1  `
                                -ResourceUrl "${{ parameters.resourceUrl }}"  `
                                -ResourceTypeName "${{ parameters.resourceTypeName }}"
        
      write-host "##vso[task.logdetail]Setting '${{ parameters.varName }}' variable to $resourceToken"
      write-host "##vso[task.setvariable variable=${{ parameters.varName }};]$resourceToken"
  target:
    settableVariables:
    - ${{ parameters.varName }}