name: 'Getting a token for accessing the resouce'
description: 'Get Azure Access Token for an specific resource'
inputs:
  creds:
    description: 'Azure credentials for the service principal to log in'
    required: true
  resourceurl:
    description: 'URL of the resource you need to authenticate against'
    required: true
outputs:
  token:
    description: "Authentication Token"
    value: ${{ steps.adquire-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - name: Logining in into Azure
      uses: Azure/login@v1
      with:
        creds: ${{ inputs.creds }}
        enable-AzPSSession: true
    - id: adquire-token
      name: Adquiring access token
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name Az.Accounts -AllowClobber -Force
        $context = Get-AzContext
        $resourceToken = (Get-AzAccessToken -ResourceUrl ${{ inputs.resourceurl}} -DefaultProfile $context).Token
        
        write-host "::debug::Set the token variable to value $resourceToken"
        write-host "::set-output name=token::$resourceToken"