parameters:
- name: environment
  type: string
  default: 'dev'
- name: sqlpackageReport
  type: string
- name: outputpath
  type: string
  default: .
- name: outputfile
  type: string
  default: 'deployreport.md'
- name: haltonerrors
  type: boolean
  default: true

steps:
- task: PowerShell@2
  name: validate
  displayName: 'Validating proposed changes'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##[debug]Ensuring target folder '${{ parameters.outputpath }}'"
      New-Item -Path '${{ parameters.outputpath }}' -ItemType Directory -ErrorAction SilentlyContinue

      $files = Get-ChildItem ${{ parameters.sqlpackageReport }} | select FullName -ExpandProperties FullName
      $ignorable = $true
      $errors = $false

      Write-Host "##[debug]The following files were identified: $files"

      ForEach($report in $files)
      {
        $packageAnalysis = scripts/actions/validate-sqlpackage/Parse-SqlProfileReport.ps1  `
                              -Environment "${{ parameters.environment }}"  `
                              -SqlPackageReport $report  `
                              -OutputFilePath "${{ parameters.outputpath }}/${{ parameters.outputfile }}"  `
                              -HaltOnDataIssues ${{ '$' }}${{ parameters.haltonerrors }} `
                              -Platform "devops"
        
        $ignorable = $ignorable -and $packageAnalysis.ignorable
        $errors = $errors -or $packageAnalysis.errors
      }

      write-host "##[debug]Setting 'ignorable' variable to $ignorable"
      write-host "##[debug]Set the 'errors' variable to $errors"
      write-host "##vso[task.setvariable variable=ignorable;]$ignorable"
      write-host "##vso[task.setvariable variable=errors;]$errors"
  target:
    settableVariables:
    - ignorable
    - errors
