parameters:
- name: resourceGroup
  type: string
- name: profile
  type: string
  default: ''
- name: databaseServer
  type: string
  default: ''
- name: databaseName
  type: string
  default: ''
- name: label
  type: string
  default: 'cicd-job-$(System.JobId)'
- name: authtoken
  type: string
- name: synapseWorkspace
  type: boolean
  default: true
- name: creds
  type: string
- name: condition
  type: boolean
  default: true

steps:
- task: AzurePowerShell@5
  displayName: 'Identifying proposed changes'
  condition: ${{ parameters.condition }}
  inputs:
    azureSubscription: ${{ parameters.creds }}
    azurePowerShellVersion: LatestVersion
    ScriptPath: 'scripts/actions/synapse-snapshot/New-AzSynapseRestorePoint.ps1'
    ScriptArguments: >
      -ResourceGroup "${{ parameters.resourceGroup }}"  
      -PublishingProfilePath "${{ parameters.profile }}" 
      -DatabaseServer "${{ parameters.databaseServer }}" 
      -DatabaseName "${{ parameters.databaseName }}" 
      -AuthToken "${{ parameters.authtoken }}" 
      -Label "${{ parameters.label }}"
      -SynapseWorkspace ${{ '$' }}${{ parameters.synapseWorkspace }}
      -Platform "devops"