parameters:
- name: action
  type: string
- name: sourcepath
  type: string
- name: profile
  type: string
  default: ''
- name: databaseServer
  type: string
  default: ''
- name: databaseName
  type: string
  default: ''
- name: authtoken
  type: string
  default: true
- name: outputpath
  default: .
- name: outputfile
  default: 'deployreport.xml' 

steps:
- task: PowerShell@2
  displayName: 'Identifying proposed changes'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##[debug]Ensuring target folder '${{ parameters.outputpath }}'"
      New-Item -Path '${{ parameters.outputpath }}' -ItemType Directory -ErrorAction SilentlyContinue
      
      Write-Host "##[debug]Looking for dacpac files at '${{ parameters.sourcepath }}'"
      $PACKAGE_PATHS = Get-ChildItem "${{ parameters.sourcepath }}" | select Name -ExpandProperty Name

      ForEach($PACKAGE in $PACKAGE_PATHS)
      {
        Write-Host "##[debug]Runing ${{ parameters.action }} on package $PACKAGE"

        $SQLPACKAGE_ARGS=@("/action:${{ parameters.action }}", `
                           "/sourcefile:${{ parameters.sourcepath }}/$PACKAGE", `
                           "/Profile:${{ parameters.profile }}", `
                           "/AccessToken:${{ parameters.authtoken }}")
        
        if ('${{ parameters.databaseServer }}' -ne '')
        {
          $SQLPACKAGE_ARGS+="/TargetServerName:${{ parameters.databaseServer }}"
        }

        if ('${{ parameters.databaseName }}' -ne '')
        {
          $SQLPACKAGE_ARGS+="/TargetDatabaseName:${{ parameters.databaseName }}"
        }

        if ('${{ parameters.action }}' -ne 'Publish')
        {
          $PACKAGE_NAME=$PACKAGE.Split('.')[0]

          $SQLPACKAGE_ARGS+="/OutputPath:${{ parameters.outputpath }}/$PACKAGE_NAME.${{ parameters.outputfile }}"
          $SQLPACKAGE_ARGS+="/OverwriteFiles:True"
        }

        Write-Host "##[debug]SqlPackage args are '$SQLPACKAGE_ARGS'"
        & "C:\Program Files\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe" $SQLPACKAGE_ARGS
      }

      