name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: build
      PROFILE_PATH: profiles
      ENVIRONMENT_PREFIX: dev

    steps:
      - uses: actions/checkout@v2

      - name: Getting packages to deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - id: sql-login
        name: Adquiring SQL Access Token
        uses: ./.github/actions/azure-resource-login
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          resource-url: "https://database.windows.net"
      
      - id: deploy-report
        name: Identifying proposed changes
        uses: ./.github/actions/run-sqlpackage
        with:
          action: 'DeployReport'
          sourcepath: $PWD/${ARTIFACT_NAME}
          outputpath: $PWD/${ARTIFACT_NAME}/${ENVIRONMENT_PREFIX}
          outputfile: deployreport.xml
          profile: ${{ github.workspace }}/${{ env.PROFILE_PATH }}/${{ env.ENVIRONMENT_PREFIX }}.profile.xml
          authtoken: ${{ steps.sql-login.outputs.token }}
      
      - id: validate-deploy
        name: Validating proposed changes
        uses: ./.github/actions/validate-sqlpackage
        with:
          environment: ${{ env.ENVIRONMENT_PREFIX }}
          sqlpackage-report: $PWD/${{ env.ARTIFACT_NAME }}/${ENVIRONMENT_PREFIX}/*.xml
          outputfile: ${{ env.ENVIRONMENT_PREFIX }}.deployreport.MD
          haltonerrors: true

      - id: deploy-target
        name: Deploying changes to target
        uses: ./.github/actions/run-sqlpackage
        with:
          action: 'Publish'
          sourcepath: $PWD/${ARTIFACT_NAME}
          profile: ${{ github.workspace }}/${{ env.PROFILE_PATH }}/${{ env.ENVIRONMENT_PREFIX }}.profile.xml
          authtoken: ${{ steps.sql-login.outputs.token }}
      
      - name: Publishing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: ${{ env.ENVIRONMENT_PREFIX }}.deployreport.MD