
name: CI

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!docs/**'
    - '!README.md'
  pull_request:
    branches: [ main ]
    paths:
    - '**'
    - '!docs/**'
    - '!README.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARTIFACTS_PATH: build
      PROFILE_PATH: profiles
      ENVIRONMENT_PREFIX: dev

    steps:
      - uses: actions/checkout@v2

      - name: Installing SQL Data Tools
        run: |
          sudo apt-get install libunwind8
          wget -progress=bar:force -q -O azuredatastudio-linux.deb https://go.microsoft.com/fwlink/?linkid=2168339 \
            && sudo dpkg -i azuredatastudio-linux.deb \
            && rm azuredatastudio-linux.deb
          wget -progress=bar:force -q -O sqlpackage.zip \
            https://aka.ms/sqlpackage-linux \
            && unzip -qq sqlpackage.zip -d /opt/sqlpackage \
            && chmod a+x /opt/sqlpackage/sqlpackage \
            && rm sqlpackage.zip

      - name: Building DACPAC
        run: |
          dotnet build src/**/*.sqlproj \
            /p:NetCoreBuild=true \
            /p:NETCoreTargetsPath=/usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/3.0.0-release.110 \
            /p:Configuration=Release \
            /p:OutputPath=$PWD/${ARTIFACTS_PATH}
          echo "PACKAGE_NAME=$(find ${ARTIFACTS_PATH} -name '*.dacpac' -exec basename {} \;)" >> $GITHUB_ENV
          echo "::debug::Package built with name: $PACKAGE_NAME"

      - id: sql-login
        name: Adquiring SQL Access Token
        uses: ./.github/actions/login-sql-database
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Identifying proposed changes
        run: |
          /opt/sqlpackage/sqlpackage \
            /action:DeployReport \
            /sourcefile:$PWD/${ARTIFACTS_PATH}/${PACKAGE_NAME} \
            /Profile:${{ github.workspace }}/${PROFILE_PATH}/${ENVIRONMENT_PREFIX}.profile.xml \
            /AccessToken:${{ steps.sql-login.outputs.token }} \
            /outputpath:$PWD/${ARTIFACTS_PATH}/deployreport.xml
      
      - name: Validating proposed changes
        shell: pwsh
        run: |
          ${{ github.workspace }}/scripts/Parse-SqlProfileReport.ps1 -Environment "${{ env.ENVIRONMENT_PREFIX }}" -SqlPackageReport "$PWD/${{ env.ARTIFACTS_PATH }}/deployreport.xml" -OutputFilePath "${{ env.ARTIFACTS_PATH }}/deployreport.MD"

      - name: Publishing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.ARTIFACTS_PATH }}/*
