
name: CI

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!docs/**'
    - '!README.md'
  pull_request:
    branches: [ main ]
    paths:
    - '**'
    - '!docs/**'
    - '!README.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARTIFACTS_PATH: build
      PROFILE_PATH: profiles
      ENVIRONMENT_PREFIX: dev

    steps:
      - uses: actions/checkout@v2

      - id: dotnet-build
        name: Building DACPAC
        uses: ./.github/actions/dotnet-data-build
        with:
          configuration: 'Release'
          solution: src/**/*.sqlproj
          outputpath: $PWD/${ARTIFACTS_PATH}
  
      - id: sql-login
        name: Adquiring SQL Access Token
        uses: ./.github/actions/azure-resource-login
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          resourceurl: "https://database.windows.net"
      
      - id: deploy-report
        name: Identifying proposed changes
        uses: ./.github/actions/run-sqlpackage
        with:
          action: 'DeployReport'
          sourcepath: $PWD/${ARTIFACTS_PATH}
          outputpath: $PWD/${ARTIFACTS_PATH}
          profile: ${{ github.workspace }}/${PROFILE_PATH}/${ENVIRONMENT_PREFIX}.profile.xml
          authtoken: ${{ steps.sql-login.outputs.token }}
      
      - name: Validating proposed changes
        shell: pwsh
        run: |
          ${{ github.workspace }}/scripts/Parse-SqlProfileReport.ps1 -Environment "${{ env.ENVIRONMENT_PREFIX }}" -SqlPackageReport "$PWD/${{ env.ARTIFACTS_PATH }}/deployreport.xml" -OutputFilePath "${{ env.ARTIFACTS_PATH }}/deployreport.MD"

      - name: Publishing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.ARTIFACTS_PATH }}/*
